# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

name: Azure_Kinect_ROS_Driver-$(SourceBranchName)-$(Date:yyyyMMdd)-$(Rev:rrr)

trigger:
  batch: false
  branches:
    include:
    - master
    - develop
    - melodic

jobs:
- job: WindowsMelodic
  displayName: Windows Melodic

  pool:
    vmImage: 'vs2017-win2016'

  steps:

  - checkout: self
    clean: "all"
    fetchDepth: 20
    lfs: false
    persistCredentials: true
    submodules: true

  # Install Chcolatey
  - powershell: Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

  # Ensure Git is installed through chocolatey
  - powershell: choco install git -y

  # Install ROS
  - powershell: choco source add -n=ros-win -s="https://roswin.azurewebsites.net/api/v2" --priority=1
  - powershell: choco upgrade ros-melodic-desktop -y --execution-timeout=0
